# Generated by Django 4.2.9 on 2024-01-04 18:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientuser',
            name='status',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='operationuser',
            name='status',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='clientuser',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='operationuser',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
