# Generated by Django 4.2.9 on 2024-01-06 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_filesystem'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewUserOtp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=30)),
                ('otp', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
