# Generated by Django 4.2.9 on 2024-01-07 07:55

import api.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_newuserotp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filesystem',
            name='file',
            field=models.FileField(upload_to='Uploads/', validators=[api.validators.validate_file_extension]),
        ),
    ]
